let actOne = 1;
function work() {
    console.log('work1 start-1');
    console.log('work1 start');
    console.log('work1 start-2');
    console.log('work1 start');
    console.log('work1 start-3');
    console.log('work1 start');
    console.log('work1 start-4');
    console.log('work1 start');
    console.log('work1 start-5');
    console.log('work1 start');
    console.log('work1 start-6');
    console.log('work1 start');
    console.log('work1 start-7');
    console.log('work1 start');
    console.log('work1 start-8');
    console.log('work1 start');
    console.log('work1 start-9');
    console.log('work1 start');
    console.log('work1 start-0');
    console.log('work1 start-10');
    console.log('work1 start-11');
    console.log('work1 start-12');
    console.log('work1 start-13');
    console.log('work1 start-14');
    console.log('work1 start-15');
    console.log('work1 start-16');
    console.log('work1 start-17');
    console.log('work1 start-18');
    console.log('work1 start-19');
    console.log('work1 start-20');
}